version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js..."
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs

  pre_build:
    commands:
      - echo "Making deployment scripts executable..."
      - chmod +x scripts/*.sh

  build:
    commands:
      - echo "Running build (if needed)..."
      # If your backend needs a build step, add it here.
      # Example: npm run build

  post_build:
    commands:
      - echo "Build complete. Preparing artifact..."

artifacts:
  base-directory: backend
  files:
    - '**/*'
